#!/usr/bin/env bash

CLASSPATH='target/test-classes:target/classes:lib/junit-4.10.jar'

main() {
	if [ "$1" = 'test' ]; then
		shift;
		run_tests "$@";
	else
		run_main "$@"
	fi
	}

run_tests() {
	# run passed test, or run all in `test` dir
	if [ "$#" != '0' ]; then
		jr org.junit.runner.JUnitCore "$@"
	else
		jr org.junit.runner.JUnitCore $(find test -type f | tr '\n' ' '  | sed -e 's~test/~~g' -e 's~/~.~g' -e 's~.java~~g')
	fi
	}

run_main() {
	MAINCLASS=${1-com.scalyr.s3search.Main}; shift;
	echo "running $MAINCLASS $@ ..."
	jr $MAINCLASS "$@"
	}

jr() {
	java -Dfile.encoding=UTF-8 -classpath "$CLASSPATH" "$@"
	}

main "$@"
